feat(amazon-eks-pod-identity-webhook): allow a set of configuration fields to be templated
jkroepke/helm-charts pull request #63
Opened 2024-12-17 10:59 UTC by tiagoposse

This PR introduces the usage of the helm tpl function for a set of deployment fields, making it possible to (in my case) use global values to configure individual audiences, prefixes and endpoints per cluster

2024-12-17 11:30 UTC, jkroepke approved these changes

2024-12-17 11:30 UTC, jkroepke requested changes
Please bump the chart version, thanks!

2024-12-17 14:52 UTC, tiagoposse commented
Done 👍

2024-12-17 15:45 UTC, jkroepke commented on charts/amazon-eks-pod-identity-webhook/templates/deployment.yaml
> +            - --sts-regional-endpoint={{ tpl .Values.config.stsRegionalEndpoint . }}
Looking at CI, stsRegionalEndpoint is a bool, but needs a string.

I guess `{{ print .Values.config.stsRegionalEndpoint }}` should help here.

2025-04-08 12:06 UTC, jkroepke commented
@tiagoposse what about doing it for 

```
            {{- if .Values.config.extraArgs }}
            {{- toYaml .Values.config.extraArgs | nindent 12 }}
            {{- end }}
```

as well?

2025-04-08 12:21 UTC, tiagoposse commented
The toYaml should convert everything to string anyways, but, imo, since it's an arbitrary "extra" value, it's up to the user of the chart to ensure the things they pass here are correct. If you disagree and want something like (quick semi-code):
```
{{ range $x := extraArgs }}
- {{ print $x }}
{{- end }}
```
also happy to do it

2025-04-09 06:07 UTC, jkroepke commented
This should work

```
            {{- if .Values.config.extraArgs }}
            {{- tpl (toYaml .Values.config.extraArgs) $ | nindent 12 }}
            {{- end }}
```

like here: https://github.com/prometheus-community/helm-charts/blob/0b60795bb66a21cd368b657f0665d67de3e49da9/charts/prometheus-blackbox-exporter/templates/_helpers.tpl#L240-L242

2025-04-09 06:14 UTC, tiagoposse commented
added this now

2025-04-09 06:21 UTC, merged

2025-04-09 06:21 UTC, jkroepke commented
thanks